package de.htwg.battleship.observer;

public enum Event {
	SET_ROWBOAT,
	SET_DESTRUCTOR,
	SET_FLATTOP,
	SHOW_MENU,
	ON_ACTION,
	SHOW_PLAYERS_FIELD,
	SHOW_BOTS_FIELD,
	ON_STATUS,
	CHEAT,
	GAME_FINISHED,
	ON_REPAINT
}