package gui;

import java.util.Enumeration;

import javax.swing.ButtonGroup;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

import controller.Controller;

public class BattleshipShipSetter extends JFrame {
	
	private final int ONE = 1;
	private final int TWO = 2;
	private int ship;
	private Controller controller;
	/**
     * Creates new form NewJFrame
     */
    public BattleshipShipSetter(int ship, Controller controller) {
    	this.controller = controller;
    	this.ship = ship;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                        
    private void initComponents() {
    	JDialog dialog = new JDialog();
    	dialog.setLocationRelativeTo(null);
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JTFxPos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFyPos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JRBhorizontal = new javax.swing.JRadioButton();
        JRBvertical = new javax.swing.JRadioButton();
        JLship = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bitte Schiff setzen!");
        setAlwaysOnTop(true);
        setResizable(false);
        dialog.setVisible(true);

        jLabel1.setText("X-Position:");

        jLabel2.setText("Y-Position:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		jButton1ActionPerformed(evt);
        	}
        });

        buttonGroup1.add(JRBhorizontal);
        JRBhorizontal.setSelected(true);
        JRBhorizontal.setText("Horizontal");

        buttonGroup1.add(JRBvertical);
        JRBvertical.setText("Vertikal");
        String s = "Bitte das Ruderboot setzen!";

        if (ship == ONE) {
        	s = "Bitte den Zerstörer setzen!";
        } else if (ship == TWO) {
        	s = "Bitte den Flugzeugträger setzen!";
        }
        JLship.setText(s);

        dialog.setContentPane(jPanel1);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(JLship)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFxPos)
                            .addComponent(JTFyPos, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JRBhorizontal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(JRBvertical)
                        .addGap(74, 74, 74))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLship)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFxPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFyPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBhorizontal)
                    .addComponent(JRBvertical))
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialog.setModal(true);
        pack();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	String s, t;
    	boolean alignment = false;
    	s = JTFxPos.getText();
    	t = JTFyPos.getText();
    	if (getSelectedRadio(buttonGroup1) == JRBvertical) {
    		alignment = true;
    	}
    	if (s == null || t == null) {
    		BattleshipGUIUtils.noInputerror();
    	} else if (controller.checkSetShipPosition(alignment) != 0) {
    		// Error
    	} else {
    		if (ship == ONE) {
    			controller.setHumanDestructor(Integer.parseInt(s), Integer.parseInt(t), alignment);
    		} else if (ship == TWO) {
    			controller.setHumanFlattop(Integer.parseInt(s), Integer.parseInt(t), alignment);
    		} else {
    			controller.setHumanRowboat(Integer.parseInt(s), Integer.parseInt(t));
    		}
    	}
    }
    
    public static JRadioButton getSelectedRadio(ButtonGroup group) {
        for (Enumeration eRadio=group.getElements(); eRadio.hasMoreElements(); ) {
            //Iterating over the Radio Buttons
            JRadioButton radioButton = (JRadioButton)eRadio.nextElement();
            //Comparing radioButtons model with groups selection
            if (radioButton.getModel() == group.getSelection()) {
                return radioButton;
            }
        }
        return null;
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel JLship;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton JRBhorizontal;
    private javax.swing.JRadioButton JRBvertical;
    private javax.swing.JTextField JTFxPos;
    private javax.swing.JTextField JTFyPos;
    // End of variables declaration           
}

